branches:
  only:
  - fuerte
  - fuerte-devel
  - groovy
  - groovy-devel
  - hydro
  - hydro-devel
  - indigo
  - indigo-devel
  - master
  
matrix:
  allow_failures:
  - compiler: clang

notifications:
  email:
  - Fabien.Spindler@inria.fr

env:
  global:
    secure: ldI5kV88XCBoLIVeA8sFAeDX+OwAfHpEvfB0cwuSdRKAnhcK4DRsfIYPkQoibZ70AzuWF6OfD84QNcq90hGgDeUFnhnmFy1J5IrPtT3YawYfxvM75jQECgwGPb4v8RSBzzVZEYxGFVJMm8xiBZ7jiN8GjaV2gr22C3dtgOS6HNY=

script: ./.travis/build

before_install: ./.travis/before_install

language: cpp

compiler:
- clang
- gcc

#after_success:: ./.travis/after_success
